### ISSUE TITLE
Příklady na práci s proměnnými: mistake in exercise 8.

### ISSUE THREAD

**Issue by jana-rovnakova** [czechitas/java-uvod-do-programovani-1#1]
"Příklady na práci s proměnnými"
Exercise 8:

Zadejte vzdálenost v metrech: 10 
 V různých jednotkách: 

Actual:
 0.008 mi 
Expected: 
0.006 mi

because: 0.01 km = 0.00621 mile.

**Comment by shinedeveloper** [comment]
Fixed. Thank you for reporting :-)
